name: 'Install Dependencies'
description: 'Install Python, upgrade pip, install Poetry, and install project and dependencies'
inputs:
  install-with:
    description: 'dependency group names to install with'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install poetry
      run: python -m pip install poetry==2.1.1

    - name: Cache the virtualenv
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

    - name: Install Dependencies
      run: python -m poetry install $INSTALL_WITH
      env:
        INSTALL_WITH: ${{ inputs.install-with != '' && join(' --with ', inputs.install-with) || '' }}
