name: Depoy Battlesnake API

on: push

permissions:
  id-token: write
  contents: read
env:
  AWS_REGION: us-west-2

jobs:
  test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install poetry
        run: python -m pip install poetry==2.1.1

      - name: Cache the virtualenv
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        run: python -m poetry install

      - name: Pytest
        run: python -m poetry run python -m pytest -sxv
